spring.application.name=gestion_usuarios_service

server.port=8081

spring.datasource.url=jdbc:mysql://curso-db.cyw92qy0exqq.us-east-1.rds.amazonaws.com:3306/gestion_usuarios_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=admin
spring.datasource.password=admin1234561

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.swagger-ui.path=/swagger-ui.html