spring.application.name=curso-service

server.port=8084

spring.datasource.url=jdbc:mysql://curso-db.cyw92qy0exqq.us-east-1.rds.amazonaws.com:3306/curso-db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=admin
spring.datasource.password=admin1234561

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.swagger-ui.path=/swagger-ui.html